source "https://rubygems.org"
gem "bcrypt"
gem "capybara"
gem "puma"
gem "rack-test"
gem "require_all"
gem "rspec"
gem "rubocop"
gem "rubocop-performance"
gem "rubocop-rails"
gem "rubocop-rspec"
gem "sequel"
gem "simplecov"
gem "sinatra"
gem "activesupport"
gem "sqlite3", "~> 1.5.4"

